# Generated by Django 2.2.28 on 2026-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('SVM', 'SVM'), ('CNN', 'CNN')], max_length=10)),
                ('accuracy', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('fscore', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'algorithm_result',
            },
        ),
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('depressed_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset_record',
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_filename', models.CharField(max_length=255)),
                ('prediction_result', models.CharField(choices=[('Normal', 'Normal'), ('Depressed', 'Depressed')], max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prediction_history',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
